spring.profiles.active=local
spring.sql.init.mode=never
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
server.port=8080
app.jwtSecret=JMEtJVoYQJjnezzUxVz5TJbwcAGozv2qaSFek68U3Ec=
app.jwtExpirationMs=3600000
app.base-url=http://localhost:8080

cloudinary.cloud_name=dzpbkbpxu
cloudinary.api_key=951586867191758

cloudinary.api_secret=1gfIouR3y6Kxzt7SW9CzjZMq11U

opencage.api.key=631480d5c1394cc683b8f2cf644ef7ee
resend.api.key=re_iHZqMmLg_2PDUAK2RQ6WTPVS5doUu5ACR
